### ISSUE TITLE
Search should have option to exclude titles that are not displayed

### ISSUE THREAD

**Issue by paul-mediakitchen** [cgkineo/adapt-search#51]
It would be useful to have the option for the search results not to display titles that are not displayed. For example if I enter "Block 1 title" as the title for a block but do not have a Display title for this block, the string "Block" and "title" are being found if I search for them.

You cannot leave the Block title blank and it would be useful to be able to give it a meaningful title without this appearing in the search results.

**Comment by moloko** [comment]
as a workaround you could add 'block' and 'title' to the 'Ignored words' list...

**Comment by oliverfoster** [comment]
It's probably because of this default setting. You can have it stop searching for "title" by removing this bit https://github.com/cgkineo/adapt-search/blob/master/js/search-algorithm.js#L28-L32.
Unfortunately it doesn't look as though this is configurable in the AAT as that `_searchAttributes` doesn't feature in the schema https://github.com/cgkineo/adapt-search/blob/master/properties.schema#L144-L311.

The example json gives a better impression of correct settings https://github.com/cgkineo/adapt-search/blob/master/example.json#L35-L86
